const data = {
  products: [
    {
      _id: "1",
      name: "slim shirt",
      category: "shirts",
      image: "./images/picture1.jpg",
      price: 220,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      _id: "2",
      name: "fit shirt",
      category: "shirts",
      image: "./images/picture2.jpg",
      price: 220,
      brand: "Adidas",
      rating: 4,
      numReviews: 20,
      description: "high quality products",
    },
    {
      _id: "3",
      name: "long shirt",
      category: "shirts",
      image: "./images/picture3.jpg",
      price: 120,
      brand: "Zara",
      rating: 4,
      numReviews: 14,
      description: "high quality products",
    },
    {
      _id: "4",
      name: "slim pants",
      category: "pant",
      image: "./images/picture4.jpg",
      price: 90,
      brand: "Puma",
      rating: 4.5,
      numReviews: 200,
      description: "high quality products",
    },
    {
      _id: "5",
      name: "slim Pajama",
      category: "Pajama",
      image: "./images/picture5.jpg",
      price: 220,
      brand: "Pajama",
      rating: 4.5,
      numReviews: 100,
      description: "high quality products",
    },
    {
      _id: "6",
      name: "slim Pajama",
      category: "Pajama",
      image: "./images/picture6.jpg",
      price: 50,
      brand: "Pajama",
      rating: 4.5,
      numReviews: 90,
      description: "high quality products",
    },
  ],
};

export default data;
